version: 0.0
os: linux
files:
- source: target/live-execution-dashboard-0.0.1-SNAPSHOT.jar
  destination: /home/ec2-user/javaapp
- source: scripts/startup.sh
  destination: /home/ec2-user/javaapp
- source: scripts/shutdown.sh
  destination: /home/ec2-user/javaapp
hooks:
  ApplicationStop:
  - location: scripts/shutdown.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/startup.sh
    timeout: 300
    runas: root
